(function(){
'use strict';
const TF_VERSION=1;
const STOP=new Set('the a an and or to of for in on at with from by is are be as it this that my your our we i you they then than into out up down can should would could make use'.split(' '));
const clone=x=>JSON.parse(JSON.stringify(x));
const clean=s=>String(s??'').trim().replace(/\s+/g,' ');
const uid=()=>globalThis.crypto?.randomUUID?.()||`tf-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const now=()=>new Date().toISOString();
const words=s=>[...new Set(clean(s).toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>2&&!STOP.has(w)))];
const jaccard=(a,b)=>{a=new Set(words(a));b=new Set(words(b));if(!a.size&&!b.size)return 0;const inter=[...a].filter(x=>b.has(x)).length;return inter/(new Set([...a,...b]).size||1)};
const hashText=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(36)};
function normIdea(x={},order=0){return {id:x.id||uid(),text:clean(x.text),status:['idea','feature','parked','rejected'].includes(x.status)?x.status:'idea',priority:Math.max(0,Math.min(2,+x.priority||0)),locked:!!x.locked,pinned:!!x.pinned,tags:Array.isArray(x.tags)?[...new Set(x.tags.map(clean).filter(Boolean))].slice(0,16):[],dependsOn:Array.isArray(x.dependsOn)?[...new Set(x.dependsOn.filter(Boolean))]:[],notes:clean(x.notes),source:x.source||'timeforge',sourceRawIds:Array.isArray(x.sourceRawIds)?[...new Set(x.sourceRawIds.filter(Boolean))]:[],provenance:x.provenance||null,created:x.created||now(),updated:x.updated||x.created||now(),order:Number.isFinite(x.order)?x.order:order}}
function normSession(s={}){s=s||{};return {schema:3,id:s.id||uid(),title:clean(s.title)||'Untitled walk product',started:s.started||null,ended:s.ended||null,ideas:Array.isArray(s.ideas)?s.ideas.map(normIdea):[],commands:Array.isArray(s.commands)?clone(s.commands):[],raw:Array.isArray(s.raw)?s.raw.map(r=>({id:r.id||uid(),at:r.at||r.created||now(),text:clean(r.text),source:r.source||'typed'})).filter(r=>r.text):[],questions:Array.isArray(s.questions)?clone(s.questions):[],constraints:Array.isArray(s.constraints)?clone(s.constraints):[],decisions:Array.isArray(s.decisions)?clone(s.decisions):[],selectedIdeaId:s.selectedIdeaId||null,created:s.created||now(),updated:s.updated||now()}}
function inferProvenance(session){const s=normSession(session);for(const idea of s.ideas){if(idea.sourceRawIds.length){idea.provenance='direct';continue}let best=null,bestScore=0;for(const raw of s.raw){let score=jaccard(idea.text,raw.text);if(clean(idea.text).toLowerCase()===clean(raw.text).toLowerCase())score=1;if(score>bestScore){best=raw;bestScore=score}}if(best&&bestScore>=.34){idea.sourceRawIds=[best.id];idea.provenance=bestScore===1?'direct':'inferred'}else idea.provenance='unlinked'}return s}
function normalizeImport(input){let originalRoot=null,session=null,archive=[];if(input?.kind==='dwf'&&input.session)return {kind:'dwf',session:inferProvenance(input.session),archive:Array.isArray(input.archive)?input.archive.map(normSession):[],originalRoot:clone(input.originalRoot)};if(input?.timeforgeVersion===TF_VERSION&&Array.isArray(input.branches))return {kind:'timeforge',state:input};if(input?.v===3&&input.current){originalRoot=clone(input);session=input.current;archive=Array.isArray(input.archive)?input.archive:[]}else if(input?.schema===3||Array.isArray(input?.ideas)){session=input;archive=[]}else throw new Error('Unsupported file. Import a Dexter Walk Forge v3 backup/session or Timeforge export.');session=inferProvenance(session);return {kind:'dwf',session,archive:archive.map(normSession),originalRoot}}
function createState(imported){if(imported.kind==='timeforge')return normalizeState(imported.state);const mainId=uid(),stamp=now(),base=clone(imported.session);return {timeforgeVersion:TF_VERSION,projectId:base.id,title:base.title,created:stamp,updated:stamp,activeBranchId:mainId,compareTargetId:mainId,branches:[{id:mainId,name:'main',parentId:null,forkEventId:null,created:stamp,baseSnapshot:clone(base),session:clone(base),events:[],checkpoints:[{id:uid(),eventId:null,at:stamp,label:'Imported baseline',session:clone(base)}]}],archive:clone(imported.archive||[]),originalRoot:clone(imported.originalRoot),meta:{importKind:'dwf'}}}
function normalizeState(x){const s=clone(x);s.timeforgeVersion=TF_VERSION;s.branches=Array.isArray(s.branches)?s.branches:[];for(const b of s.branches){b.session=inferProvenance(b.session);b.baseSnapshot=normSession(b.baseSnapshot||b.session);b.events=Array.isArray(b.events)?b.events:[];b.checkpoints=Array.isArray(b.checkpoints)&&b.checkpoints.length?b.checkpoints:[{id:uid(),eventId:null,at:b.created||now(),label:'Recovered baseline',session:clone(b.session)}]}if(!s.branches.some(b=>b.id===s.activeBranchId))s.activeBranchId=s.branches[0]?.id||null;if(!s.branches.some(b=>b.id===s.compareTargetId))s.compareTargetId=s.branches[0]?.id||null;return s}
const branch=(state,id=state.activeBranchId)=>state.branches.find(b=>b.id===id)||null;
function checkpointFor(b,index){const i=Math.max(0,Math.min(index,b.checkpoints.length-1));return clone(b.checkpoints[i]?.session||b.session)}
function appendEvent(state,branchId,type,payload,mutator,label){const b=branch(state,branchId);if(!b)throw new Error('Branch not found');const before=clone(b.session);mutator(b.session);b.session.updated=now();const event={id:uid(),at:now(),type,payload:clone(payload||{}),beforeHash:hashText(JSON.stringify(before)),afterHash:hashText(JSON.stringify(b.session)),label:label||type};b.events.push(event);b.checkpoints.push({id:uid(),eventId:event.id,at:event.at,label:event.label,session:clone(b.session)});state.updated=event.at;return event}
function forkBranch(state,{fromBranchId=state.activeBranchId,checkpointIndex=null,name='branch'}={}){const src=branch(state,fromBranchId);if(!src)throw new Error('Source branch not found');const idx=checkpointIndex==null?src.checkpoints.length-1:checkpointIndex;const snap=checkpointFor(src,idx);const cp=src.checkpoints[Math.max(0,Math.min(idx,src.checkpoints.length-1))];const id=uid();const b={id,name:clean(name)||'branch',parentId:src.id,forkEventId:cp?.eventId||null,created:now(),baseSnapshot:clone(snap),session:clone(snap),events:[],checkpoints:[{id:uid(),eventId:null,at:now(),label:`Forked from ${src.name}`,session:clone(snap)}]};state.branches.push(b);state.activeBranchId=id;state.updated=now();return b}
function ideaMap(s){return new Map((s.ideas||[]).map(x=>[x.id,x]))}
function valueKey(x){return JSON.stringify({text:x.text,status:x.status,priority:x.priority,locked:x.locked,pinned:x.pinned,tags:x.tags,dependsOn:x.dependsOn,notes:x.notes})}
function listDiff(source,target){const out=[],a=ideaMap(source),b=ideaMap(target);for(const [id,x] of a){if(!b.has(id))out.push({key:`idea:add:${id}`,kind:'added',entity:'idea',id,label:x.text,source:clone(x),target:null});else if(valueKey(x)!==valueKey(b.get(id)))out.push({key:`idea:change:${id}`,kind:'changed',entity:'idea',id,label:x.text,source:clone(x),target:clone(b.get(id))})}for(const [id,x] of b){if(!a.has(id))out.push({key:`idea:remove:${id}`,kind:'removed',entity:'idea',id,label:x.text,source:null,target:clone(x)})}for(const type of ['constraints','decisions','questions']){const sa=new Map((source[type]||[]).map(x=>[x.id||hashText(x.text),x])),tb=new Map((target[type]||[]).map(x=>[x.id||hashText(x.text),x]));for(const [id,x] of sa)if(!tb.has(id))out.push({key:`${type}:add:${id}`,kind:'added',entity:type,id,label:x.text||String(x),source:clone(x),target:null});for(const [id,x] of tb)if(!sa.has(id))out.push({key:`${type}:remove:${id}`,kind:'removed',entity:type,id,label:x.text||String(x),source:null,target:clone(x)})}return out}
function applyDiffItem(targetSession,item){if(item.entity==='idea'){const i=targetSession.ideas.findIndex(x=>x.id===item.id);if(item.kind==='removed'){if(i>=0)targetSession.ideas.splice(i,1)}else if(i>=0)targetSession.ideas[i]=clone(item.source);else targetSession.ideas.push(clone(item.source));return}const arr=targetSession[item.entity]||(targetSession[item.entity]=[]),i=arr.findIndex(x=>(x.id||hashText(x.text))===item.id);if(item.kind==='removed'){if(i>=0)arr.splice(i,1)}else if(i>=0)arr[i]=clone(item.source);else arr.push(clone(item.source))}
function mergeSelected(state,sourceId,targetId,keys){const src=branch(state,sourceId),dst=branch(state,targetId);if(!src||!dst)throw new Error('Branch not found');if(src.id===dst.id)throw new Error('Choose a different comparison target');const diffs=listDiff(src.session,dst.session).filter(d=>keys.includes(d.key));if(!diffs.length)return null;return appendEvent(state,dst.id,'merge',{sourceBranchId:src.id,keys:[...keys]},s=>{for(const d of diffs)applyDiffItem(s,d)},`Merged ${diffs.length} change${diffs.length===1?'':'s'} from ${src.name}`)}
function addIdea(state,branchId,text){text=clean(text);if(!text)return null;return appendEvent(state,branchId,'idea:add',{text},s=>{const raw={id:uid(),at:now(),text,source:'timeforge'};s.raw.push(raw);s.ideas.push(normIdea({id:uid(),text,source:'timeforge',sourceRawIds:[raw.id],provenance:'direct',order:s.ideas.length,created:raw.at}))},'Idea added')}
function patchIdea(state,branchId,id,patch){return appendEvent(state,branchId,'idea:patch',{id,patch},s=>{const x=s.ideas.find(i=>i.id===id);if(!x)throw new Error('Idea not found');Object.assign(x,clone(patch),{updated:now()});if(['parked','rejected'].includes(x.status))x.locked=false;if(x.locked){x.status='feature';x.priority=Math.max(1,x.priority)}},'Idea changed')}
function addRecord(state,branchId,type,text){if(!['constraints','decisions','questions'].includes(type))throw new Error('Bad record type');text=clean(text);if(!text)return null;return appendEvent(state,branchId,`${type}:add`,{text},s=>s[type].push({id:uid(),text,created:now(),...(type==='questions'?{resolved:false}:{})}),`${type.slice(0,-1)} added`)}
function lineage(branchObj,idea){const raw=(branchObj.session.raw||[]).filter(r=>(idea.sourceRawIds||[]).includes(r.id));const events=(branchObj.events||[]).filter(e=>e.payload?.id===idea.id||e.payload?.ideaId===idea.id);return {raw,events,provenance:idea.provenance||((idea.sourceRawIds||[]).length?'direct':'unlinked')}}
function readiness(s){const features=s.ideas.filter(x=>x.status==='feature').length,critical=s.ideas.filter(x=>x.status==='feature'&&x.priority===2).length,constraints=s.constraints.length,questions=s.questions.filter(x=>!x.resolved).length;return Math.max(0,Math.min(100,Math.round(Math.min(45,features*6)+Math.min(25,critical*8)+Math.min(20,constraints*5)+Math.max(0,10-questions*2))))}
function themesForSessions(sessions){const counts=new Map();for(const s of sessions)for(const i of s.ideas||[])for(const w of words(i.text))counts.set(w,(counts.get(w)||0)+1);return [...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,18).map(([term,count])=>({term,count}))}
function projectMemory(state){const main=branch(state,state.branches.find(b=>b.name==='main')?.id||state.branches[0]?.id);const sessions=[main?.session,...(state.archive||[])].filter(Boolean).map(normSession);const themes=themesForSessions(sessions);const resurfacing=[];if(sessions.length>1){for(const idea of sessions[0].ideas){let hits=0;for(const old of sessions.slice(1))if(old.ideas.some(x=>jaccard(idea.text,x.text)>=.45))hits++;if(hits)resurfacing.push({text:idea.text,hits})}}const stableConstraints=[];const allConstraints=sessions.flatMap((s,si)=>(s.constraints||[]).map(c=>({si,text:c.text||String(c)})));for(const c of allConstraints.filter(x=>x.si===0)){const hits=new Set(allConstraints.filter(x=>x.si>0&&jaccard(c.text,x.text)>=.5).map(x=>x.si)).size;if(hits)stableConstraints.push({text:c.text,hits})}return {walks:sessions.length,themes,resurfacing:resurfacing.sort((a,b)=>b.hits-a.hits).slice(0,10),stableConstraints:stableConstraints.sort((a,b)=>b.hits-a.hits).slice(0,10)}}
function recipe(state,branchId,type){const b=branch(state,branchId);if(!b)return '';const s=b.session,features=s.ideas.filter(x=>x.status==='feature'),critical=features.filter(x=>x.priority===2),nonGoals=s.ideas.filter(x=>x.status==='rejected'),later=s.ideas.filter(x=>x.status==='parked'),q=s.questions.filter(x=>!x.resolved),head=`# ${s.title}\n\nBranch: ${b.name}\nReadiness: ${readiness(s)}%\n`;
const bullets=a=>a.length?a.map(x=>`- ${x.text||x}`).join('\n'):'- None recorded';
if(type==='mvp')return `${head}\n## MVP\n${bullets((critical.length?critical:features.slice(0,5)))}\n\n## Constraints\n${bullets(s.constraints)}\n\n## Explicit non-goals\n${bullets(nonGoals)}`;
if(type==='qa')return `${head}\n## Acceptance matrix\n${features.map((x,i)=>`${i+1}. GIVEN the product is available, WHEN the user exercises “${x.text}”, THEN the behavior completes without losing local project state.`).join('\n')||'No accepted features yet.'}\n\n## Risk checks\n- Local persistence survives reload.\n- Export/import round-trip preserves accepted state.\n- Rejected ideas remain non-goals.\n- Branch-only changes do not leak into main before merge.`;
if(type==='issues')return `${head}\n## Implementation sequence\n${features.map((x,i)=>`### ${i+1}. ${x.text}\nPriority: ${x.priority===2?'critical':x.priority===1?'high':'normal'}\nDone when: behavior is implemented, integrated, and validated through the real user path.`).join('\n\n')||'No accepted features yet.'}`;
if(type==='agent')return `${head}\n## Objective\nImplement the accepted branch state without broadening scope.\n\n## Must preserve\n- Local-first operation.\n- Raw walk trace.\n- Rejected ideas as explicit non-goals.\n- Typed fallback when voice is unavailable.\n\n## Required work\n${bullets(features)}\n\n## Constraints\n${bullets(s.constraints)}\n\n## Open questions\n${bullets(q)}\n\n## Validation\nProve each changed user path in the actual runtime. Do not claim completion from source presence alone.`;
if(type==='handoff')return `${head}\n## Product state\nAccepted features:\n${bullets(features)}\n\nCritical path:\n${bullets(critical)}\n\nConstraints:\n${bullets(s.constraints)}\n\nDecisions:\n${bullets(s.decisions)}\n\nOpen questions:\n${bullets(q)}\n\nLater scope:\n${bullets(later)}\n\nNon-goals:\n${bullets(nonGoals)}\n\n## Raw trace\n${s.raw.map(r=>`- ${r.at}: ${r.text}`).join('\n')||'- None recorded'}`;
return `${head}\n## Build target\n${bullets(features)}\n\n## Critical features\n${bullets(critical)}\n\n## Constraints\n${bullets(s.constraints)}\n\n## Decisions\n${bullets(s.decisions)}\n\n## Open questions\n${bullets(q)}\n\n## Later\n${bullets(later)}\n\n## Explicit non-goals\n${bullets(nonGoals)}\n\n## Source walk trace\n${s.raw.map(r=>`- ${r.text}`).join('\n')||'- None recorded'}`}
function exportDwf(state){const main=state.branches.find(b=>b.name==='main')||state.branches[0];if(!main)throw new Error('No main branch');const root=state.originalRoot&&state.originalRoot.v===3?clone(state.originalRoot):{v:3,current:null,archive:clone(state.archive||[]),settings:{},ui:{view:'walk',query:'',status:'all',sort:'recent'},backups:[],meta:{}};const s=clone(main.session);for(const i of s.ideas){delete i.sourceRawIds;delete i.provenance}root.current=s;root.archive=clone(state.archive||root.archive||[]);return root}
function demoImport(){const t=Date.now(),iso=n=>new Date(t+n*60000).toISOString();const raw=[{id:'r1',at:iso(0),text:'I want the walk itself to be the design session and I should not have to organize anything first.',source:'typed'},{id:'r2',at:iso(3),text:'It has to work offline because I lose signal while walking Dexter.',source:'typed'},{id:'r3',at:iso(7),text:'Maybe voice is optional and typing always works.',source:'typed'}];return {kind:'dwf',session:inferProvenance({schema:3,id:'demo',title:'Walk to working app',raw,ideas:[{id:'i1',text:raw[0].text,status:'feature',priority:2,locked:true,created:raw[0].at},{id:'i2',text:raw[1].text,status:'feature',priority:2,locked:true,created:raw[1].at},{id:'i3',text:raw[2].text,status:'feature',priority:1,created:raw[2].at}],constraints:[{id:'c1',text:'Core workflow must remain usable offline.',created:iso(4)}],decisions:[],questions:[{id:'q1',text:'What is the smallest useful handoff?',resolved:false,created:iso(8)}]}),archive:[],originalRoot:null}}
globalThis.TimeforgeCore={TF_VERSION,clone,clean,uid,now,words,jaccard,hashText,normIdea,normSession,inferProvenance,normalizeImport,createState,normalizeState,branch,checkpointFor,appendEvent,forkBranch,listDiff,mergeSelected,addIdea,patchIdea,addRecord,lineage,readiness,projectMemory,recipe,exportDwf,demoImport};
})();